name: Pull Request

on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  build_test_scan_and_push:
    name: Lint, test & build image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      evaluate-complexity:
        name: Evaluate Code complexity
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v2
            with:
              fetch-depth: 0
              ref: ${{ github.event.pull_request.head.ref }}
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: 3.10.0
          - name: Install Wily
            run: pip install wily==1.20.0
          - name: Build cache and diff
            id: wily
            run: |
              wily build src/ tests/
              DIFF=$(wily diff src/ tests/ --no-detail -r origin/${{ github.event.pull_request.base.ref }})
              echo "$DIFF"
              # Build multine output
              DIFF="${DIFF//'%'/'%25'}"
              DIFF="${DIFF//$'\n'/'%0A'}"
              DIFF="${DIFF//$'\r'/'%0D'}"
              echo "::set-output name=diff::$DIFF"
          - name: Find current PR
            uses: jwalton/gh-find-current-pr@v1
            id: findPr
          - name: Add Wily PR Comment
            uses: marocchino/sticky-pull-request-comment@v2
            if: steps.findPr.outputs.number && steps.wily.outputs.diff != ''
            with:
              recreate: true
              number: ${{ steps.findPr.outputs.number }}
              message: |
                ```
                ${{ steps.wily.outputs.diff }}
                ```
          - name: Add Wily PR Comment
            uses: marocchino/sticky-pull-request-comment@v2
            if: steps.findPr.outputs.number && steps.wily.outputs.diff == ''
            with:
              recreate: true
              number: ${{ steps.findPr.outputs.number }}
              message: |
                ```
                Wily: No changes in complexity detected.
                ```

      - name: Environment variables
        id: vars
        run: |
          echo "::set-output name=tag::$(git rev-parse --short HEAD)"
          echo "::set-output name=app::deiteo/kafka-client"

      - uses: ./.github/actions/lint-test-build-scan
        with:
          app: ${{ steps.vars.outputs.app }}
          tag: ${{ steps.vars.outputs.tag }}
